### ISSUE TITLE
Comprehensive Roles Report

### ISSUE THREAD

**Issue by mtotty36078** [piyush-khandelwal-sp/idn-admin-console#126]
Wondering if it is feasible to finally get a comprehensive roles report out of IDN.
It would be really nice if the report broke down each role with 
Role Name
Role Criteria
      Access Profile(s)
          Entitlement(s)
Members
This is never easy to look at from within the UI or Search. Seems it would be extremely helpful to keep track of what you have configured!

**Comment by piyush-khandelwal-sp** [comment]
Hi @mtotty36078 looks like basically you are looking for a csv dump of get each role API? hopefully ppl can help enhance the tool or feel free to give it a go.. We still haven't implemented (and need help) with #18 which can probably break in a large environment during this implementation..

**Comment by piyush-khandelwal-sp** [comment]
@mtotty36078 new version coming which doesn't have 100% what you want but the following features

Adds the following in the download report (Roles -> Manage Roles -> Download)

* Criteria detail if Criteria Based
* Identity List if not Criteria Based
* Access Profiles attached to role

Please do enhance it more to you linking. Would appreciate the help.
