### ISSUE TITLE
Correlate an uncorrelated account in a source.

### ISSUE THREAD

**Issue by hacharya1** [piyush-khandelwal-sp/idn-admin-console#204]
Correlate an uncorrelated account in a source using Admin console

**Comment by piyush-khandelwal-sp** [comment]
Hi @hacharya1 don't think there is an API for this from what I am aware. It's a file upload and download only and in IDN UI

**Comment by hacharya1** [comment]
Hi Piyush - What I mean in this request is - let's say I have a user record "MJohnson" sitting in Uncorrelated Status in the Flat file source. In the Admin console if I pull that source, can it provide me the list of uncorrelated accounts in the source? If so, then I find MJohnson in that list, provide his Sailpoint Username and when I click "Correlate account", it correlates to his Identity Profile?
